[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000
remappings = ["forge-std/=lib/forge-std/src/", "@uniswap/=node_modules/@uniswap/", "@openzeppelin/=node_modules/@openzeppelin/"]
verbosity = 1

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4
